### ISSUE TITLE
docs for nf-test nf-core integration

### ISSUE THREAD

**Issue by Emiller88** [nf-core/website#2050]
@sateeshperi could you expand on this one?
```[tasklist]
### Tasks
- [x] Update module tutorial
- [ ] https://github.com/nf-core/website/pull/2059
- [ ] Add migration from pytest-workflow to nf-test tutorial
- [ ] https://github.com/nf-core/website/pull/2085
- [ ] Add separate nf-test assertions docs
```
